Controllers/Api/MoviesController.cs
using AutoMapper;
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Vidly.Dtos;
using Vidly.Models;

namespace Vidly.Controllers.Api
{
    public class MoviesController : ApiController
    {
        private ApplicationDbContext _context;
        public MoviesController()
        {
            _context = new ApplicationDbContext();
        }

        //GET /api/movies
        public IHttpActionResult GetMovies() {

            return Ok(_context.Movies
                .Include(m => m.Genre)
                .ToList()
                .Select(Mapper.Map<Movie, MovieDto>));
        
        }
        //GET /api/movies/id
        public IHttpActionResult GetMovie(int id)
        {
            var movie =_context.Movies.SingleOrDefault(m => m.Id == id);
            if (movie == null)
                return NotFound();
            return Ok(Mapper.Map<Movie, MovieDto>(movie));
        }

        //POST /api/movies
        [HttpPost]
        public IHttpActionResult CreateMovie(MovieDto movieDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var movie = Mapper.Map<MovieDto, Movie>(movieDto);
            movie.Date = DateTime.Now;
            _context.Movies.Add(movie);
            _context.SaveChanges();
            movieDto.Id = movie.Id;
            return Created(new Uri(Request.RequestUri + "/" + movie.Id), movieDto);
        }
        [HttpPut]
        public IHttpActionResult UpdateCustomer(int id,MovieDto movieDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var movie = _context.Movies.SingleOrDefault(m => m.Id == id);
            if (movie == null)
                return NotFound();
            Mapper.Map(movieDto, movie);
            _context.SaveChanges();
            return Ok(movie);
            
        }
        [HttpDelete]
        public IHttpActionResult DeleteMovie(int id)
        {
            var movie = _context.Movies.SingleOrDefault(m => m.Id == id);
            if (movie == null)
                return NotFound();
            _context.Movies.Remove(movie);
            _context.SaveChanges();
            return Ok(Mapper.Map<Movie, MovieDto>(movie));
        }
    }
}

Views/Movies/Details.cshtml
@model Vidly.Models.Movie
@{
    ViewBag.Title = "Details";
}

<h2>@Model.Name</h2>

<ul>
    <li>Genre: @Model.Genre</li>
    <li>Release Date: @Model.ReleaseDate</li>
    <li>Date Added: @Model.Date</li>
    <li>Number in Stock @Model.NumberInStock</li>
</ul>

Views/Movies/List.cshtml
@model List<Vidly.Models.Movie>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Movies</h2>
@Html.ActionLink("NEW MOVIE", "New", "Movies")


    <table id ="movies" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Movie</th>
                <th>Genre</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
        
    </table>


@section scripts
{
    <script>

        $(document).ready(function () {
            var table = $("#movies").DataTable({
                ajax: {
                    url: "api/movies/",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "name",
                        render: function (data, type, movie) {
                            return "<a href='/movies/edit/" + movie.id + "'>" + movie.name + "</a>";
                        }
                    },
                    {
                        data: "genre.name",

                    },
                    {
                        data: "id",
                        render: function (data) {
                            return "<button class='btn-link js-delete' data-movie-id=" + data + ">Delete</button>";
                        }
                    }

                ]
            });

            $("#movies").on("click", ".js-delete", function () {
                var button = $(this);
                bootbox.confirm("Sure want to delete this movie?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "api/movies/"+ button.attr("data-movie-id"),
                            method: "DELETE",
                            success: function () {
                                table.row(button.parents("tr")).remove().draw();
                            }
                        });
                    }
                });
            });
        })
    </script>
    }

Views/Movies/New.cshtml
@model Vidly.ViewModels.NewMovieViewModel
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model.Movie == null || Model.Movie.Id==0)
{
    <h2>New Movie</h2>
}
else
{
    <h2>Edit Movie</h2>}
@using (Html.BeginForm("Save", "Movies"))
{

    @Html.ValidationSummary(true, "Please fix the following errors.")
    <div class="form-group">
        @Html.LabelFor(m => m.Movie.Name)
        @Html.TextBoxFor(m => m.Movie.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Movie.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Movie.ReleaseDate)
        @Html.TextBoxFor(m => m.Movie.ReleaseDate, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Movie.ReleaseDate)
    </div>
    <div class="form-group">

        @Html.LabelFor(m => m.Movie.GenreId)
        @Html.DropDownListFor(m => m.Movie.GenreId, new SelectList(Model.Genres, "Id", "Name"), "Select Genre", new { @class = "form-control" })
        
    </div>
    <div class="form-group">

        @Html.LabelFor(m => m.Movie.NumberInStock)
        @Html.TextBoxFor(m => m.Movie.NumberInStock, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Movie.NumberInStock)
    </div>
    @Html.Hidden("Movie.Id",(Model.Movie != null) ? Model.Movie.Id :  0)
    @Html.HiddenFor(m => m.Movie.Id)
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Save</button>









}

Views/Movies/ReadOnlyList.cshtml
@model List<Vidly.Models.Movie>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Movies</h2>

    <table id ="movies" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Movie</th>
                <th>Genre</th>
                
            </tr>
        </thead>
        <tbody>

        </tbody>
        
    </table>


@section scripts
{
    <script>

        $(document).ready(function () {
            var table = $("#movies").DataTable({
                ajax: {
                    url: "api/movies/",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "name",
                        render: function (data, type, movie) {
                            
                            return "<a href='/movies/details/" + movie.id + "'>" + movie.name + "</a>";
                        }
                    },
                    {
                        data: "genre.name",

                    },
                   

                ]
            });

           
        })
    </script>
    }